### ISSUE TITLE
package installation issue

### ISSUE THREAD

**Issue by usmanshahid001** [digidotcom/xbee-csharp#5]
hii i am unable to install xbeeLibrary.core through nugdet manager as it is giving error of target netFramework..Severity Code Description Project File Line Suppression State Error Could not install package 'XBeeLibrary.Core 1.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by usmanshahid001** [comment]
hi any help?
i tried several things but no luck......

**Comment by hgonzaleDigi** [comment]
Hello @usmanshahid001,

What version of the .NET framework are you running with?
Also, what sort of project are you trying to import the package to (Xamarin, .NET Core, .NET Framework, ...)?

**Comment by usmanshahid001** [comment]
i have tried several .NET framework from 2.0 to 8.0. i am using .NET Framework

**Comment by hgonzaleDigi** [comment]
And what version of Visual Studio are you creating the project with?
And what type of project are you creating? a Console App (.NET Framework) or a diferent one?

I guess this has to do with the .NET framework version you have selected for the project. I tried using .NET Framework 4.7.2 and the nuget package was successfully installed.

**Comment by usmanshahid001** [comment]
it is Windows Form App

**Comment by usmanshahid001** [comment]
visual studio 2017

**Comment by usmanshahid001** [comment]
this is my app.config file
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7.2" />
    </startup>
</configuration>

**Comment by usmanshahid001** [comment]
app.config file
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7.2" />
    </startup>
</configuration>

**Comment by hgonzaleDigi** [comment]
Well, I just created a new Windows Forms App (.NET Framework) project with an installation of Visual Studio 2017 (15.9.8) and I was able to successfully import the XBeeLibrary.Core NuGet package.

The Target framewok of the app is .NET Framework 4.7.2 (to check for yours go to your project, right click on it and go to Properties->Application).

Also, we don't have official support for this library on Windows. There is a branch in this Github repository with an non-tested support, that is why it is not official.

**Comment by usmanshahid001** [comment]
i have checked it is 4.7.2 .i am able to install other nuget packages but facing problem for this.however thanks for your cooperation.

**Comment by usmanshahid001** [comment]
Attempting to gather dependency information for package 'XBeeLibrary.Core.1.0.0' with respect to project 'lastTry', targeting '.NETFramework,Version=v4.7.2'.console message when i hit install

**Comment by usmanshahid001** [comment]
ok i downloaded the package and simply added the DLL files to my references.it worked

**Comment by usmanshahid001** [comment]
how to get xbeeLibrary.windows now?

**Comment by hgonzaleDigi** [comment]
I am glad you were able to install the libraries manually, although the problem you described should not have happened. Again, sorry for the inconveniences, but we were not able to reproduce your issue.

As for the Windows support, it is in a [branch ](https://github.com/digidotcom/xbee-csharp/tree/windows_module) in this git repository. That branch is not fully tested nor officially released, so be aware that you may encounter some errors. Now, to work with it, you just need to checkout the code of that branch into your pc, and import the corresponding DLL as you did with the core library.

Both Windows and Bluetooth layers are built on top of the core, so this means, both libraries, core and Windows, are required for your project to be able to communicate with an XBee over the serial interface.
