### ISSUE TITLE
Error forming IMEIAddress

### ISSUE THREAD

**Issue by RobDevAthena** [digidotcom/xbee-csharp#7]
Great library!! Thanks for the work!! I am trying to transfer data between two XBEE3 devices. Setup and connected to cellular system correctly, can connect to DIGI echo server etc so I know that is all working well.
When running any of your communication examples (connecttoEchoServerSample is easiest) I set the correct com port but when the sample runs it throws an error at this section 

IMEIAddress = new XBeeIMEIAddress(XBee64BitAddr.Value);

XBee64BitAddr.Value is null so it errors out, but in the documentation it says that cellular devices should always return null. I'm a little confused as to what to do. Any help would be appreciated

![image](https://user-images.githubusercontent.com/14104273/88323174-1298d280-ccdf-11ea-9e23-88bb8fb9e97b.png)

Visual Studio 2019, DIGI XBEE3 LTE/NB-IoT Dev kit

Rob

**Comment by rubenmoral** [comment]
Hi @RobDevAthena,

Thanks for reporting this issue. We have verified that it was a bug affecting XBee Cellular devices, it's now fixed on the `master` branch.

Best regards.
